//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyzers
    {
        public Analyzers()
        {
            this.PerformedServices = new HashSet<PerformedServices>();
        }
    
        public int AnalyzerId { get; set; }
        public string Name { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<PerformedServices> PerformedServices { get; set; }
    }
}
