//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompanies
    {
        public InsuranceCompanies()
        {
            this.InsuranceInvoices = new HashSet<InsuranceInvoices>();
            this.Patients = new HashSet<Patients>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string AccountNumber { get; set; }
        public string BIC { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<InsuranceInvoices> InsuranceInvoices { get; set; }
        public virtual ICollection<Patients> Patients { get; set; }
    }
}
