//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceInvoices
    {
        public int InvoiceId { get; set; }
        public int InsuranceCompanyId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual InsuranceCompanies InsuranceCompanies { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
