//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServices
    {
        public OrderServices()
        {
            this.PerformedServices = new HashSet<PerformedServices>();
        }
    
        public int OrderServiceId { get; set; }
        public int OrderId { get; set; }
        public int ServiceId { get; set; }
        public string Status { get; set; }
        public Nullable<int> ExecutionTimeSeconds { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
        public virtual ICollection<PerformedServices> PerformedServices { get; set; }
    }
}
