//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.InsuranceInvoices = new HashSet<InsuranceInvoices>();
            this.OrderServices = new HashSet<OrderServices>();
        }
    
        public int OrderId { get; set; }
        public int PatientId { get; set; }
        public string Barcode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Status { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<InsuranceInvoices> InsuranceInvoices { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual ICollection<OrderServices> OrderServices { get; set; }
    }
}
