//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformedServices
    {
        public int PerformedServiceId { get; set; }
        public int OrderServiceId { get; set; }
        public System.DateTime PerformedDate { get; set; }
        public int AnalyzerId { get; set; }
        public string Result { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual Analyzers Analyzers { get; set; }
        public virtual OrderServices OrderServices { get; set; }
    }
}
