//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.SystemUsers = new HashSet<SystemUsers>();
        }
    
        public int RoleId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SystemUsers> SystemUsers { get; set; }
    }
}
