//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServices
    {
        public int UserServiceId { get; set; }
        public int UserId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
